export const sampleActionTypes = {
  GETSAMPLES_SUCCESS: "GETSAMPLES_SUCCESS",
  ADDSAMPLE_SUCCESS: "ADDSAMPLE_SUCCESS"
};

export const userActionTypes = {
  GETCURRENTUSER_SUCCESS: "GETCURRENTUSER_SUCCESS",
  LOGOUT: "LOGOUT"
};
